adds favicon
LeoTuet/ui-we-want-to-sleep pull request #58
Opened 2022-02-17 23:41 UTC by quintus-luis

2022-02-18 11:10 UTC, Aloso requested changes
I really like this. However, while this icon looks good on a dark background, it's difficult to see on white. Would you mind adding a dark background to the icon? I'm thinking of this color: `#100522`

2022-02-18 11:13 UTC, quintus-luis commented
Good Point!

2022-03-25 11:40 UTC, 94726 requested changes

2022-03-25 11:40 UTC, 94726 commented on index.html
> +    <link rel="mask-icon" href="favicon.svg">
```suggestion
    <link rel="mask-icon" href="/favicon.svg">
```

2022-03-25 11:44 UTC, 94726 approved these changes

2022-03-25 11:49 UTC, Aloso requested changes
`logo256.png` is 512x512 pixels, please rename it to `logo512.png`.

Since you renamed `manifest.json` to `site.webmanifest`, you need to change it in the `index.html` as well.

I personally don't like that the manifest is no longer formatted. It's not worthwhile to make a file unreadable just to save a few bytes (if that was your intention).

2022-03-25 11:51 UTC, LeoTuet commented
> `logo256.png` is 512x512 pixels, please rename it to `logo512.png`.
> 
> Since you renamed `manifest.json` to `site.webmanifest`, you need to change it in the `index.html` as well.
> 
> I personally don't like that the manifest is no longer formatted. It's not worthwhile to make a file unreadable just to save a few bytes (if that was your intention).

I overlooked that - all

2022-03-25 12:02 UTC, Aloso approved these changes
LGTM

2022-03-25 16:06 UTC, merged