Feature/switch dark light
LeoTuet/ui-we-want-to-sleep pull request #63
Opened 2022-02-23 20:59 UTC by LeoTuet

The Switch Button is only for temporary use. This pr is only about brining the basic functionality to main

2022-02-23 21:04 UTC, quintus-luis requested changes

2022-02-23 21:04 UTC, quintus-luis commented on public/index.html
> +    <script>
We should find another way for doing this.
the index.html should never be touched

2022-02-23 21:04 UTC, quintus-luis commented on src/components/ThemeToggle.tsx
> +      {isDark && (<img src={halfMoon} alt={"Half Moon - Toggle Button for Light Mode"} width={"50"}/>)}
should be the same img tag.
=> src={isDark ? halfMoon : sheep}

2022-02-23 21:47 UTC, Aloso requested changes
I'll finish the review tomorrow.

2022-02-23 21:47 UTC, Aloso commented on src/components/ThemeToggle.tsx
> +      console.log("setting")
Remove this line

2022-02-23 21:47 UTC, Aloso commented on src/components/ThemeToggle.tsx
> +  const handleChangeTheme = useCallback(() => {
The use of `useCallback` seems unnecessary. The callback doesn't have any dependencies and isn't used as a dependency either. I think you can use a normal (arrow) function.

2022-02-23 21:47 UTC, Aloso commented on src/components/ThemeToggle.tsx
> +    }
I think this can be improved to be more DRY. Both branches do essentially the same.

2022-02-23 21:47 UTC, Aloso commented on src/components/ThemeToggle.tsx
> +  const [isDark, setIsDark] = useState(false)
I don't like using a boolean for this. A better approach might be using an enum or a union type (`type Theme = "light" | "dark"`).

2022-02-24 11:09 UTC, Aloso commented
I tested it in Firefox and it doesn't work. It set's `localStorage.theme` to `"light"` before checking the color scheme preference.

2022-03-14 19:55 UTC, quintus-luis approved these changes

2022-03-15 09:51 UTC, Aloso commented on src/components/ThemeToggle.tsx
> +      localStorage.removeItem("theme");
I believe you should update the `theme` variable in this event listener.

2022-03-15 09:59 UTC, Aloso requested changes

2022-03-15 09:59 UTC, Aloso commented on src/components/ThemeToggle.tsx
> +        src={theme ? halfMoon : sheep}
I don't think this has the intended effect, considering that `theme` has the type `Theme | undefined`.

2022-03-15 21:52 UTC, LeoTuet commented on src/components/ThemeToggle.tsx
> +  }, []);
Does that really make sense ? We would need to pass it from `App` > `Home` > `IntroSection` > `ThemeToggle` right ?

2022-03-16 00:27 UTC, quintus-luis commented on src/components/ThemeToggle.tsx
> +  }, []);
we have a redux store. just put it in there

2022-03-16 07:41 UTC, LeoTuet commented on src/components/ThemeToggle.tsx
> +  }, []);
Should the store then in gerneral handle the switching of the theme ?

2022-03-16 07:45 UTC, quintus-luis commented on src/components/ThemeToggle.tsx
> +  }, []);
No. Reading out the current Theme based on the browser settings must be done in the App, but you don’t need the useState anymore and can access the information from anywhere

2022-03-17 11:40 UTC, Aloso approved these changes
LGTM

2022-03-17 11:41 UTC, merged

2022-03-17 12:07 UTC, LeoTuet commented
> Thanks for working on this!

Thank you for your feedback!! It helped me quite a lot.