#64  implements vite setup
LeoTuet/ui-we-want-to-sleep pull request #66
Opened 2022-03-16 21:44 UTC by 94726

This PR replaces the setup initially created by `create-react-app` with `Vite`
You should definetly checkout this PR and see the speed yourself.

2022-03-16 21:46 UTC, quintus-luis approved these changes

2022-03-16 23:01 UTC, LeoTuet approved these changes
LGTM

2022-03-17 12:06 UTC, Aloso requested changes

2022-03-17 12:06 UTC, Aloso commented on package.json
>      "react-scripts": "5.0.0",
`react-scripts` is a dependency of `create-react-app`. I think if we use Vite, we should remove this.

2022-03-17 12:06 UTC, Aloso commented on package.json
> +    "test": "react-scripts test",
This should be replaced with `jest`. How to test React/TS apps with Vite is explained [here](https://codingwithmanny.medium.com/quick-jest-setup-with-vitejs-react-typescript-82f325e4323f), for example.

2022-03-18 10:57 UTC, Aloso commented
@94726 Could you please also remove the line from the Dockerfile that installs `react-scripts`? Then I think this is ready to merge.

2022-03-18 11:18 UTC, 94726 commented
> @94726 Could you please also remove the line from the Dockerfile that installs `react-scripts`? Then I think this is ready to merge.

Oh sorry, didn't see it. Wonder why it was added in the first place 😕.

Gonne change it later.

2022-03-19 18:18 UTC, Aloso approved these changes
LGTM

2022-03-21 06:55 UTC, merged