New language/theme selection
LeoTuet/ui-we-want-to-sleep pull request #87
Opened 2022-04-02 20:49 UTC by Aloso

Puts this in the top right corner:

![tr](https://user-images.githubusercontent.com/15658558/161400529-afa55095-b2b3-476c-8fd4-bc2781b5dc76.png)

And in the footer:

![footer-bright](https://user-images.githubusercontent.com/15658558/161400675-858d8b38-f397-454a-a09e-49ef0da03fbd.png)

![footer](https://user-images.githubusercontent.com/15658558/161400534-f99967a5-a66f-442c-98e1-630fc8e6eeaa.png)

This makes the language selection more accessible by showing it at the top of the start page. The theme can now be changed on every page in the footer. I hope the new UI is more intuitive than the old one.

2022-04-02 22:52 UTC, 94726 commented
I love the design, looks great. But I'm not sure about the language switch. I don't know whether anything is planned, but if we end up adding more languages, it would probably end up needing to be changed. 

Going to review the code sometime today.

2022-04-02 23:01 UTC, Aloso commented
Adding 1 or 2 more languages wouldn't be an issue with this design. How many other translations would you be able to contribute? More importantly, which other languages do you think are needed? I assumed that there aren't any students who speak neither German nor English.

2022-04-02 23:17 UTC, 94726 commented
> How many other translations would you be able to contribute

Just roasting me here lol. I could try my best at polish though, but nearly no one speaks that anyways.

> I assumed that there aren't any students who speak neither German nor English.

Yeah you're probably right.

2022-04-03 00:23 UTC, 94726 requested changes

2022-04-03 00:23 UTC, 94726 commented on src/components/SelectSlider.tsx
> +type Option<T extends string> = T | { name: T; node: ReactNode };
I took quite a bit of time, trying to understand the props.
Some little documentation about what all of these do in conjunction with each other like ->
```ts
value: T; // String identifying the selected element
```
maybe what role  `T` or `name` of `type Option` play in that (might choose a better name than `name` like `value` 🤷).

2022-04-03 00:23 UTC, 94726 commented on src/sections/Footer.tsx
> +  const { theme } = useTheme();
remove the now unnecessary stuff

2022-04-03 20:51 UTC, LeoTuet commented
> I love the design, looks great. But I'm not sure about the language switch. I don't know whether anything is planned, but if we end up adding more languages, it would probably end up needing to be changed.
> 
> Going to review the code sometime today.

we will stick to only english and german

2022-04-03 20:57 UTC, LeoTuet approved these changes

2022-04-03 20:57 UTC, 94726 approved these changes
👍

2022-04-03 21:00 UTC, merged